"""Add identification fields and update quiz result model

Revision ID: 4f069b1ada7b
Revises: beb52a6c8d9d
Create Date: 2026-02-02 22:21:59.764123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f069b1ada7b'
down_revision = 'beb52a6c8d9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mental_health_quiz_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('risk_level', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('recommendation', sa.Text(), nullable=True))
        batch_op.drop_column('result')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('teacher_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('professional_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('counselor_license', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('child_registration_number', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('child_registration_number')
        batch_op.drop_column('counselor_license')
        batch_op.drop_column('professional_id')
        batch_op.drop_column('teacher_id')
        batch_op.drop_column('student_id')

    with op.batch_alter_table('mental_health_quiz_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('recommendation')
        batch_op.drop_column('risk_level')
        batch_op.drop_column('score')

    # ### end Alembic commands ###
